### ISSUE TITLE
Error writing to database 

### ISSUE THREAD

**Issue by emmamendelsohn** [ecohealthalliance/doltr#48] opened 2022-07-25 20:57 UTC
as appears in our scraper running on GH actions

```
• start target disease_key_in_db
✖ error target disease_key_in_db
• end pipeline: 1.828 seconds
Error in tar_throw_run(target$metrics$error) : 
  No such process, pid 3278, ???
```

**Comment by noamross** [comment] 2022-07-25 22:50
I think the issue here has to do with the way `doltr` finds and selects the dolt server process to attach to.  If I recall correctly, it may be as simple as the fact that it starts the server and then tries to extract the process ID, but it takes a moment for the server to start up fully and thus extracting the process ID fails.  In this case we just need a short `Sys.sleep()` or ideally a loop waiting until the process is ready before connecting, here: https://github.com/ecohealthalliance/doltr/blob/main/R/server.R#L89-L93

Otherwise it may have something to do with how dolt searches for pre-existing server processes before attempting to start a new one, here: https://github.com/ecohealthalliance/doltr/blob/main/R/server.R#L59-L67

**Comment by noamross** [comment] 2022-07-25 22:52
Oh, it might also be an issue with `dolt_path()` returning the right dolt binary in that same function.

**Comment by n8layman** [comment] 2022-07-29 18:47
Notes:

Each target fails trying a different PID. This suggests that each target is trying to generate a new process instead of recycling one connection to the db. 

I.e. one target fails with `no such process, pid 5587, ???`, and another fails with `No such process, pid 5373, ???` within the same automation run.

**Comment by n8layman** [comment] 2022-07-29 18:59
Currently suspect that `dp <- dp[dp$name == "dolt" & dp$status == "running",]` is failing within `dolt_server_find` because dolt has changed the name associated with their process ID's.

**Comment by n8layman** [comment] 2022-07-29 19:11
Nope. That seems to work alright.

**Comment by n8layman** [comment] 2022-07-29 19:43
Added a branch hotfix-issue_48 to try adding `Sys.sleep(0.25)` on line 94 of server.R between `process$new` call and reading process id with `proc$as_ps_handle()`. Testing from dtra-ml by updating renv.lock to point to the doltr hotfix branch and running the automation.

**Comment by n8layman** [comment] 2022-07-29 21:53
That didn't fix it. Narrowed down the error to a problem with `process$new`. I think when running local targets this part of server.R searches for and returns a pre-existing instance of p but on automation it has to create a new one from scratch. The automation error message can be reproduced when `process$new` encounters an error such as:

```Starting server with Config HP=\"127.0.0.1:3306\"|T=\"0\"|R=\"false\"|L=\"info\"\nPort 3306 already in use.\n```

doltr tries an alternate port if 3306 is in use so it might not be a port issue. However something is erroring out here. Next step is to force it to write an error and output logs to check what's going on.

When successful:
```
> proc
PROCESS 'dolt', running, pid 84193.
> proc$as_ps_handle()
<ps::ps_handle> PID=84193, NAME=dolt, AT=2022-07-29 21:42:20
```

On failure:
```
> proc
PROCESS 'dolt', finished.
> proc$as_ps_handle()
<ps::ps_handle> PID=84057, NAME=???, AT=2022-07-29 21:41:09
```

**Comment by n8layman** [comment] 2022-07-30 01:08
Actually now I think on it the automation never seems to use the default port of 3306. I wonder why? Maybe it isn't finding pre-existing dolt processes... And If it can't find a previous connection to DOLT I wonder if the trouble is having two different connections to the server from the same container using different ports.

**Comment by n8layman** [comment] 2022-08-01 05:38
proccess$new terminates with the following error suggesting an improperly set mysql global variable might be the cause.
The error seems to come from line 35 of [https://github.com/dolthub/go-mysql-server/blob/v0.12.0/sql/errors.go#L24](https://github.com/dolthub/go-mysql-server/blob/v0.12.0/sql/errors.go#L24). No idea yet why this works locally but not via github automations.

```
Failed to start server. Bad Configuration
failed to set net_read_timeout. Error: Variable 'net_read_timeout' can't be set to the value of '0'
```

**Comment by n8layman** [comment] 2022-08-01 17:21
Okay so it turns out there were 3 problems:

1. `The net_read_timeout can't be set to 0` error was fixed by the fis server timeout commit to main. However this update wasn't snapshotted and so the renv.lock file didn't reflect the change.

2. Dolt now writes a sql-server.lock file in the /dbPath/.dolt folder to ensure atomic access to local servers. Github actions was using a cached a copy of the dolt directory including the lock file thereby preventing any new processes from starting at all.

3. Dolt now puts processes to sleep when not active. doltr:::dolt_server_find() only looks for 'running' processes when attempting to recycle a server connection. Because the previous connection was writing a lock file, no further processes could start, resulting in target failure.

**Closed** 2022-08-01 18:01 UTC
